spring:
  application:
    name: market
  profiles:
    include: secret
  datasource:
    url: jdbc:mysql://localhost:3306/SejongMarketDB?serverTimezone=Asia/Seoul
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

app:
  upload:
    dir: ./uploads
    url-prefix: /uploads
