spring.application.name=demo

# DB 접속 주소 (market_db는 미리 생성해두어야 함)
spring.datasource.url=jdbc:mysql://localhost:3306/market_db?serverTimezone=Asia/Seoul
# DB 접속 아이디 (보통 root)
spring.datasource.username=root
# DB 접속 비밀번호
spring.datasource.password=본인_비밀번호
# 사용할 드라이버 클래스 명시
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 설정 (테이블 자동 생성 및 SQL 로그 출력)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true